
# Configuración de Supabase
project_id = "mwxytzuootrrudjfwsif"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
enable_signup = true

[functions.check-immersion-status]
verify_jwt = false

[functions.send-immersion-notifications]
verify_jwt = false
