
project_id = "mwxytzuootrrudjfwsif"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[realtime]
enabled = true

[functions.check-immersion-status]
verify_jwt = false

[functions.send-immersion-notifications]
verify_jwt = false
