// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozjpwwmhtsicfpybmyqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96anB3d21odHNpY2ZweWJteXFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDQ4OTIsImV4cCI6MjA2MzU4MDg5Mn0.PLARXguAgfp1XQ6m0z9jndtcVzWqnRMoT9bvGkFWp6w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);